### PR TITLE
Fix analyze endpoint

### LINKED ISSUE #8: Change data source name
API route should be changed with :datasource-name
https://github.com/mindsdb/mindsdb_js_sdk/blob/master/src/index.js#L245

### PR DESCRIPTION
**Pull request by ZoranPandovski**
* Change analyze to call new API path
* Fixes #8

### CODE REVIEW

**Comment by George3d6** [comment]
Ok, so the `whatever` in relation to your comment was there because `predictors` required a predictor name, so when the `analyze` endpoint was there you needed to pass a name (which could be `whatever` since the server didn't use it, it's just how pathing works).

The new endpoint under datasources shouldn't need that.

**Comment by George3d6** [comment]
The call should be `/datasources/<datasource_name>/analyze` and the `data_source_name` url argument shouldn't be required, if possible make those changes and test them to make sure it works correctly.

**Comment by ZoranPandovski** [comment]
Ok, the hardcoded value was removed and the name was added to the path. If (this.name) is not available will take default value.

**Comment by George3d6** [comment]
Ok, if the name is added to the path it should no longer be needed in the URL query. So remove it from there and merge the PR once that's done.

**Pull request merged**
